## vectors 101

In [4]:
import numpy as np

v = np.array([2, -1, 5])

v_len = np.linalg.norm(v)

w = np.array([10, 4, -2])
vw = np.dot(v, w)

print("Vector v =", v)
print("Length of v =", v_len)
print("Vector w =", w)
print("Dot product v.m =", vw)


Vector v = [ 2 -1  5]
Length of v = 5.477225575051661
Vector w = [10  4 -2]
Dot product v.m = 6


##Practical Scenario — “Drone hop”

In [5]:
p_start = np.array([2,1])
p_end = np.array([7,4])

d = p_start - p_end
dist = np.linalg.norm(d)
unit = d / dist
x_axis = np.dot(unit, np.array([1, 0]))

print(f"displacement: {d}")
print(f"distence: {dist}")
print(f"unit direction: {unit}")
print(f"x_axis: {x_axis}")


displacement: [-5 -3]
distence: 5.830951894845301
unit direction: [-0.85749293 -0.51449576]
x_axis: -0.8574929257125441


##  Matrices 101

In [22]:
A = np.array([[3, 1],[2, 5]])
tra = A.T
det_A = np.linalg.det(A)

if det_A != 0:
  inv_A = np.linalg.inv(A)
else:
  print("is not invertible")

print(A)
print("------------------")
print(tra)
print("------------------")
print(det_A)
print("------------------")
print(inv_A)

[[3 1]
 [2 5]]
------------------
[[3 2]
 [1 5]]
------------------
13.0
------------------
[[ 0.38461538 -0.07692308]
 [-0.15384615  0.23076923]]


##  Practical Scenario — “Rotate that hop”

In [24]:
import numpy as np

theta = np.deg2rad(30)

R = np.array([
    [np.cos(theta), -np.sin(theta)],
    [np.sin(theta),  np.cos(theta)]])

d = np.array([5, 3])

d_rot = R @ d

d_back = np.linalg.inv(R) @ d_rot

print("Rotation matrix determinant:", np.linalg.det(R))
print("Rotated vector:", d_rot)
print("Back-rotated equals original?", np.allclose(d_back, d))


Rotation matrix determinant: 1.0
Rotated vector: [2.83012702 5.09807621]
Back-rotated equals original? True
