 # Vectors 101

In [1]:
import numpy as np

v = np.random.randint(1,10,size=(4 , 2 , 3))
print(f"v shape: {v.shape}, v ndim: {v.ndim}")
print(f"Norm of v ===> {np.linalg.norm(v)}")
print("---------------------------------------------------")

w = np.random.randint(1,10,size=(4 , 3 , 2))
print(f"w shape: {w.shape}, w ndim: {w.ndim}")

dot_product = np.matmul(v, w)
print(f"Dot product of v and w ====> {dot_product}")
print("---------------------------------------------------")
print(f"dot_product shape: {dot_product.shape}, dot_product ndim: {dot_product.ndim}")

v shape: (4, 2, 3), v ndim: 3
Norm of v ===> 26.267851073127396
---------------------------------------------------
w shape: (4, 3, 2), w ndim: 3
Dot product of v and w ====> [[[ 75 113]
  [ 50  75]]

 [[ 44  69]
  [ 40  77]]

 [[ 95 119]
  [ 87 119]]

 [[133  91]
  [ 83  46]]]
---------------------------------------------------
dot_product shape: (4, 2, 2), dot_product ndim: 3


#  Practical Scenario — “Drone hop”

In [2]:
p_start = np.array([2,1])
p_end = np.array([7,4])

displacement = np.subtract(p_end, p_start)
distance = np.linalg.norm(displacement)
unit = displacement / distance
dot_x = np.dot(displacement , [1,0])

print(f"Displacement ==> {displacement}")
print(f"shape of displacement ==> {displacement.shape}")
print(f"Distance ==> {distance}")
print(f"Unit ==> {unit}")
print(f"Dot_x ==> {dot_x}")

Displacement ==> [5 3]
shape of displacement ==> (2,)
Distance ==> 5.830951894845301
Unit ==> [0.85749293 0.51449576]
Dot_x ==> 5


# Matrices 101

In [3]:
a = np.random.randint(1 , 10 , size=(2,2))
print(f"a shape ==> {a.shape}, a ndim ==> {a.ndim}")
print("-----------------------------------------------")

det_a = np.linalg.det(a)
print(f"Det of a ==> {det_a}")

a_inv = np.linalg.inv(a)
print(f"A_inv ==> {a_inv}")

a shape ==> (2, 2), a ndim ==> 2
-----------------------------------------------
Det of a ==> 52.999999999999986
A_inv ==> [[ 0.13207547 -0.01886792]
 [-0.05660377  0.1509434 ]]


 # Practical Scenario — “Rotate that hop”
# Rotate the drone’s displacement vector 30° counter-clockwise, then verify that the inverse rotation brings it back.

In [5]:
theta = np.deg2rad(30)

r = np.array([[np.cos(theta), -np.sin(theta)],
              [np.sin(theta),  np.cos(theta)]])

det_r = np.linalg.det(r)

d_rotate = np.matmul(r, displacement)
d_back_rotate = np.matmul(np.linalg.inv(r), d_rotate)

print(f"r ==> {r}")
print("---------------------------------------------")
print(f"shape of r ==> {r.shape}")
print(f"shape of d ==> {displacement.shape}")
print(f"shape of d_rotate ==> {d_rotate.shape}")
print(f"Theta ==> {theta}")
print(f"Determinant of r ==> {det_r}")
print(f"Back rotate is equal to d_roate?? ===> {np.allclose(d_back_rotate , displacement)}")

r ==> [[ 0.8660254 -0.5      ]
 [ 0.5        0.8660254]]
---------------------------------------------
shape of r ==> (2, 2)
shape of d ==> (2,)
shape of d_rotate ==> (2,)
Theta ==> 0.5235987755982988
Determinant of r ==> 1.0
Back rotate is equal to d_roate?? ===> True
