# 🔥 Assignment: Exploring PyTorch


## 🎯 Goal
This assignment evaluates your basic skills in using PyTorch, focusing on tensors, autograd, and a small training loop.



### 1️⃣ Setup and Basics
**Task:**

* Install PyTorch and check its version.

* Create a 2D tensor and print it.

In [1]:
import torch

print("PyTorch version:", torch.__version__)
x = torch.tensor([[1., 2.], [3., 4.]])
print("Tensor x:\n", x)


PyTorch version: 2.6.0+cu124
Tensor x:
 tensor([[1., 2.],
        [3., 4.]])


In [2]:
# Your turn:
# Create another tensor y of the same shape with values [[5, 6], [7, 8]].
y=torch.tensor([[5, 6], [7, 8]])





### 2️⃣ Tensor Operations 🧮
**Task:** Perform addition and matrix multiplication.

In [ ]:
z = x + y
print("Addition:\n", z)

# Convert y to float to match x's dtype for matrix multiplication
y_float = y.float()
mat_mul = x @ y_float
print("Matrix Multiplication:\n", mat_mul)

# Perform element-wise multiplication
element_wise_mul = x * y_float
print("Element-wise Multiplication:\n", element_wise_mul)

In [5]:
# Your turn:
# Perform element-wise multiplication (x * y) and print the result.
result=x*y
print("Element-wise Multiplication:\n", result)





Element-wise Multiplication:
 tensor([[ 5., 12.],
        [21., 32.]])


### 3️⃣ Autograd and Gradients ⚙️
**Task:** Enable gradient tracking and compute derivatives.

In [14]:
a = torch.tensor(3.0, requires_grad=True)
b = (a ** 2) + 2 * a + 1
b.backward()
print("Gradient of b wrt a:", a.grad)


Gradient of b wrt a: tensor(8.)


In [16]:
# Your turn:
# Create a tensor p with value 2.0 (requires_grad=True) and compute the gradient of q = p^3 + 4p.
p=torch.tensor(2.0, requires_grad=True)
q=p**3+4*p
q.backward()
print("Gradient of q wrt p:", p.grad)




tensor(16., grad_fn=<AddBackward0>)

### 4️⃣ Random Tensors 🎲
**Task:** Generate a random tensor of shape (2, 3) and find its max and min.

In [19]:
rand_tensor = torch.rand((2, 3))
print("Random Tensor:\n", rand_tensor)
print("Max:", torch.max(rand_tensor))
print("Min:", torch.min(rand_tensor))


Random Tensor:
 tensor([[0.4823, 0.5779, 0.3458],
        [0.5859, 0.4225, 0.0038]])
Max: tensor(0.5859)
Min: tensor(0.0038)


### 5️⃣ Mini Training Loop 🤖
**Task:** Train a simple linear model y = wx + b using gradient descent.

In [21]:
# Data
x_train = torch.tensor([[1.0], [2.0], [3.0]])
y_train = torch.tensor([[2.0], [4.0], [6.0]])

# Model
w = torch.randn(1, requires_grad=True)
b = torch.randn(1, requires_grad=True)

# Training
learning_rate = 0.01
for epoch in range(100):
    y_pred = w * x_train + b
    loss = torch.mean((y_pred - y_train) ** 2)
    loss.backward()

    # Update
    with torch.no_grad():
        w -= learning_rate * w.grad
        b -= learning_rate * b.grad
        w.grad.zero_()
        b.grad.zero_()

print("Trained weight:", w.item())
print("Trained bias:", b.item())


Trained weight: 1.5857030153274536
Trained bias: 0.9417575597763062


### 6️⃣ Bonus ⚡
* Convert a PyTorch tensor to a NumPy array.

* Convert it back to a PyTorch tensor.

In [22]:
# To do
x=torch.tensor([[1., 2.], [3., 4.]])
y=x.numpy()
print(y)
z=torch.from_numpy(y)
print(z)





[[1. 2.]
 [3. 4.]]
tensor([[1., 2.],
        [3., 4.]])
