# 🔥 Assignment: Exploring PyTorch

<p align="center">📢⚠️📂  </p>

<p align="center"> Please name your file using the format: <code>assignmentName_nickname.py/.ipynb</code> (e.g., <code>project1_ali.py</code>) and push it to GitHub with a clear commit message.</p>

<p align="center"> 🚨📝🧠 </p>

------------------------------------------------



## 🎯 Goal
This assignment evaluates your basic skills in using PyTorch, focusing on tensors, autograd, and a small training loop.



### 1️⃣ Setup and Basics
**Task:**

* Install PyTorch and check its version.

* Create a 2D tensor and print it.

In [5]:
import torch

print("PyTorch version:", torch.__version__)
x = torch.tensor([[1., 2.], [3., 4.]])
print("Tensor x:\n", x)


PyTorch version: 2.9.0+cpu
Tensor x:
 tensor([[1., 2.],
        [3., 4.]])


In [7]:
# Your turn:
# Create another tensor y of the same shape with values [[5, 6], [7, 8]].

y = torch.tensor([[5., 6.], [7., 8.]])
print("tensor y:\n", y)



tensor y:
 tensor([[5., 6.],
        [7., 8.]])


### 2️⃣ Tensor Operations 🧮
**Task:** Perform addition and matrix multiplication.

In [9]:
z = x + y
print("Addition:\n", z)

mat_mul = x @ y
print("Matrix Multiplication:\n", mat_mul)


Addition:
 tensor([[ 6.,  8.],
        [10., 12.]])
Matrix Multiplication:
 tensor([[19., 22.],
        [43., 50.]])


In [8]:
# Your turn:
# Perform element-wise multiplication (x * y) and print the result.


Q = x * y
print("element-wise:\n" , Q)



element-wise:
 tensor([[ 5., 12.],
        [21., 32.]])


### 3️⃣ Autograd and Gradients ⚙️
**Task:** Enable gradient tracking and compute derivatives.

In [ ]:
a = torch.tensor(3.0, requires_grad=True)
b = (a ** 2) + 2 * a + 1
b.backward()
print("Gradient of b wrt a:", a.grad)


In [12]:
# Your turn:
# Create a tensor p with value 2.0 (requires_grad=True) and compute the gradient of q = p^3 + 4p.

p = torch.tensor(2.0, requires_grad=True)
q = p **3 + 4*p
q.backward()
print("gradient of Q:\n", Q)



gradient of Q:
 tensor([[ 5., 12.],
        [21., 32.]])


### 4️⃣ Random Tensors 🎲
**Task:** Generate a random tensor of shape (2, 3) and find its max and min.

In [13]:
rand_tensor = torch.rand((2, 3))
print("Random Tensor:\n", rand_tensor)
print("Max:", torch.max(rand_tensor))
print("Min:", torch.min(rand_tensor))


Random Tensor:
 tensor([[0.5648, 0.8316, 0.9398],
        [0.8484, 0.9933, 0.7010]])
Max: tensor(0.9933)
Min: tensor(0.5648)


### 5️⃣ Mini Training Loop 🤖
**Task:** Train a simple linear model y = wx + b using gradient descent.

In [18]:
# Data
torch.manual_seed(42)
x_train = torch.tensor([[1.0], [2.0], [3.0]])
y_train = torch.tensor([[2.0], [4.0], [6.0]])

# Model
w = torch.randn(1, requires_grad=True)
b = torch.randn(1, requires_grad=True)

# Training
learning_rate = 0.01
for epoch in range(100):
    y_pred = w * x_train + b
    loss = torch.mean((y_pred - y_train) ** 2)
    loss.backward()

    # Update
    with torch.no_grad():
        w -= learning_rate * w.grad
        b -= learning_rate * b.grad
        w.grad.zero_()
        b.grad.zero_()

print("Trained weight:", w.item())
print("Trained bias:", b.item())


Trained weight: 1.750671625137329
Trained bias: 0.5667532682418823


### 6️⃣ Bonus ⚡
* Convert a PyTorch tensor to a NumPy array.

* Convert it back to a PyTorch tensor.

In [22]:
# To do

import torch
import numpy as np

a = torch.tensor([[1, 2, 3], [4, 5, 6]])
print(a)

a = a.numpy()

print(a)

tensor([[1, 2, 3],
        [4, 5, 6]])
[[1 2 3]
 [4 5 6]]


In [39]:
torch.manual_seed(42)
tensor_a = torch.ones(5)
print("create a tensor of 1:\n",tensor_a)

numpy_a = a.numpy()
print("convert tensor to numpy:\n" , numpy_a)
np.add(numpy_a, 1, out=numpy_a)
print("add +1 for test to np:\n", numpy_a)

tensor_b = torch.tensor(numpy_a)
print("back to tensor:\n",tensor_b)


create a tensor of 1:
 tensor([1., 1., 1., 1., 1.])
convert tensor to numpy:
 [8. 8. 8. 8. 8.]
add +1 for test to np:
 [9. 9. 9. 9. 9.]
back to tensor:
 tensor([9., 9., 9., 9., 9.])
