# 📓 Assignment 4 — Linear Algebra Fundamentals

*Vectors & Matrices for Everyday Coding*



## Welcome back, intrepid coder! 🚀
In this notebook-styled brief you’ll move from single-direction vectors to multi-direction matrices—core tools behind graphics, robotics, optimisation and (of course) machine-learning. Each mini-section mixes quick notes, a tiny real-world scenario, and hands-on # TODO code shaped for beginners.


## 🧭 Vectors 101

| Concept             | Quick reminder                                  |
|---------------------|--------------------------------------------------|
| Representation      | 1-D NumPy array — `np.array([x, y, z])`         |
| Length (norm)       | `np.linalg.norm(v)`                             |
| Dot / inner product | `v.dot(w)` or `np.inner(v, w)`                  |
| Unit vector         | `v / np.linalg.norm(v)`                         |


In [40]:
# Run once per session
import numpy as np

# TODO 1: create a 3-D vector named v
# TODO 2: print its length
# TODO 3: build a second vector w and output the dot product
v = np.array([[[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]],
              [[13, 14, 15, 16], [17, 18, 19, 20], [21, 22, 23, 24]]])

w = np.array([[[25, 26, 27, 28], [29, 30, 31, 32], [33, 34, 35, 36]],
              [[37, 38, 39, 40], [41, 42, 43, 44], [45, 46, 47, 48]]])
print("v:",v)
print("----------------")
print("w:",w)
print("----------------")
v_lenght=np.linalg.norm(v)
w_lenght=np.linalg.norm(w)
print("v_lenght:",v_lenght,"w_lenght:",w_lenght)
print("----------------")
v.shape
w.shape
print("v/v_lenght:",v/v_lenght)
print("----------------")
print("w/w_lenght:",w/w_lenght)

print("----------------")

print(v[0][0])

print("----------------")
print(w[0][0])
print("----------------")
print(v[0][0].dot(w[0][0]))

v: [[[ 1  2  3  4]
  [ 5  6  7  8]
  [ 9 10 11 12]]

 [[13 14 15 16]
  [17 18 19 20]
  [21 22 23 24]]]
----------------
w: [[[25 26 27 28]
  [29 30 31 32]
  [33 34 35 36]]

 [[37 38 39 40]
  [41 42 43 44]
  [45 46 47 48]]]
----------------
v_lenght: 70.0 w_lenght: 182.0
----------------
v/v_lenght: [[[0.01428571 0.02857143 0.04285714 0.05714286]
  [0.07142857 0.08571429 0.1        0.11428571]
  [0.12857143 0.14285714 0.15714286 0.17142857]]

 [[0.18571429 0.2        0.21428571 0.22857143]
  [0.24285714 0.25714286 0.27142857 0.28571429]
  [0.3        0.31428571 0.32857143 0.34285714]]]
----------------
w/w_lenght: [[[0.13736264 0.14285714 0.14835165 0.15384615]
  [0.15934066 0.16483516 0.17032967 0.17582418]
  [0.18131868 0.18681319 0.19230769 0.1978022 ]]

 [[0.2032967  0.20879121 0.21428571 0.21978022]
  [0.22527473 0.23076923 0.23626374 0.24175824]
  [0.24725275 0.25274725 0.25824176 0.26373626]]]
----------------
[1 2 3 4]
----------------
[25 26 27 28]
----------------
270


### 🚁 Practical Scenario — “Drone hop”
A mini-drone lifts off at (2 m, 1 m) and lands at (7 m, 4 m).
Calculate its displacement vector, travel distance, and orientation along the x-axis.

In [41]:
p_start = np.array([2, 1])
p_end   = np.array([7, 4])

# displacement
d = p_end - p_start          # ➡️ vector from start to end
dist = np.linalg.norm(d)     # 🏁 distance travelled
unit = d / dist              # ↗️ unit direction
dot_x = d.dot(np.array([1, 0]))  # projection on x-axis

print("Displacement:", d)
print("Distance:", dist)
print("Unit direction:", unit)
print("Dot-product with x-axis:", dot_x)


Displacement: [5 3]
Distance: 5.830951894845301
Unit direction: [0.85749293 0.51449576]
Dot-product with x-axis: 5


## 🔢 Matrices 101

| Operation              | NumPy one-liner                                  |
|------------------------|--------------------------------------------------|
| Transpose              | `A.T`                                            |
| Determinant            | `np.linalg.det(A)`                               |
| Inverse                | `np.linalg.inv(A)` (works only if `det(A) ≠ 0`)  |
| Matrix-vector multiply | `A @ v`                                          |
| Matrix-matrix multiply | `A @ B`                                          |


In [9]:
# TODO 4: build a 2×2 matrix A
# TODO 5: print its determinant
# TODO 6: if invertible, compute and print A_inv
import numpy as np
A=np.array([[1,2],[3,4]])
A
A.shape
det_A=np.linalg.det(A)
print("det_A:",det_A)
if det_A != 0:
    A_inv = np.linalg.inv(A)
    print("Inverse of A:\n", A_inv)
else:
    print("Matrix A is not invertible.")

det_A: -2.0000000000000004
Inverse of A:
 [[-2.   1. ]
 [ 1.5 -0.5]]


### 🎯 Practical Scenario — “Rotate that hop”
Rotate the drone’s displacement vector 30° counter-clockwise, then verify that the inverse rotation brings it back.

In [13]:
d=np.array([1,3])
theta = np.deg2rad(90)          # 🔄 convert degrees to radians
R = np.array([[np.cos(theta), -np.sin(theta)],
              [np.sin(theta),  np.cos(theta)]])

det_R = np.linalg.det(R)        # should be 1.0 (pure rotation)

d_rot  = R @ d                  # rotated displacement
d_back = np.linalg.inv(R) @ d_rot

print("Rotation matrix determinant:", det_R)
print("Rotated vector:", d_rot)
print("Back-rotated equals original?", np.allclose(d_back, d))


Rotation matrix determinant: 1.0
Rotated vector: [-3.  1.]
Back-rotated equals original? True
