# 🔥 Assignment: Exploring PyTorch


## 🎯 Goal
This assignment evaluates your basic skills in using PyTorch, focusing on tensors, autograd, and a small training loop.



### 1️⃣ Setup and Basics
**Task:**

* Install PyTorch and check its version.

* Create a 2D tensor and print it.

In [1]:
import torch

print("PyTorch version:", torch.__version__)
x = torch.tensor([[1., 2.], [3., 4.]])
print("Tensor x:\n", x)

PyTorch version: 2.7.1+cpu
Tensor x:
 tensor([[1., 2.],
        [3., 4.]])


In [2]:
# Your turn:
# Create another tensor y of the same shape with values [[5, 6], [7, 8]].

y = torch.tensor([[5., 6.], [7., 8.]])
print("Tensor x:\n", y)


Tensor x:
 tensor([[5., 6.],
        [7., 8.]])


### 2️⃣ Tensor Operations 🧮
**Task:** Perform addition and matrix multiplication.

In [ ]:
z = x + y
print("Addition:\n", z)

mat_mul = x @ y
print("Matrix Multiplication:\n", mat_mul)


In [3]:
# Your turn:
# Perform element-wise multiplication (x * y) and print the result.
x = torch.tensor([[1., 2.], [3., 4.]])
y = torch.tensor([[5., 6.], [7., 8.]])

result = x * y 
print(result)

tensor([[ 5., 12.],
        [21., 32.]])


torch.mul >> ضرب درایه به درایه با استفاده از متد های پای تورچ

In [ ]:
x = torch.tensor([[1., 2.], [3., 4.]])
y = torch.tensor([[5., 6.], [7., 8.]])

result = torch.mul(x, y)
print(result)

### 3️⃣ Autograd and Gradients ⚙️
**Task:** Enable gradient tracking and compute derivatives.

In [ ]:
a = torch.tensor(3.0, requires_grad=True)
b = (a ** 2) + 2 * a + 1
b.backward()  # این دستور مشتق یا گرادیان رو محاسبه میکنه

print("Gradient of b wrt a:", a.grad)

Gradient of b wrt a: tensor(8.)


In [7]:
# Your turn:
# Create a tensor p with value 2.0 (requires_grad=True) and compute the gradient of q = p^3 + 4p.

p = torch.tensor(2.0 , requires_grad=True )
q = (p**3) + 4*p
q.backward()

print("Gradient of b wrt a:", p.grad)

Gradient of b wrt a: tensor(16.)


### 4️⃣ Random Tensors 🎲
**Task:** Generate a random tensor of shape (2, 3) and find its max and min.

In [8]:
rand_tensor = torch.rand((2, 3))
print("Random Tensor:\n", rand_tensor)
print("Max:", torch.max(rand_tensor))
print("Min:", torch.min(rand_tensor))


Random Tensor:
 tensor([[0.4863, 0.3921, 0.9604],
        [0.9888, 0.0973, 0.7078]])
Max: tensor(0.9888)
Min: tensor(0.0973)


### 5️⃣ Mini Training Loop 🤖
**Task:** Train a simple linear model y = wx + b using gradient descent.

In [11]:
# Data
x_train = torch.tensor([[1.0], [2.0], [3.0]])
y_train = torch.tensor([[2.0], [4.0], [6.0]])

# Model
w = torch.randn(1, requires_grad=True)
b = torch.tensor(0.0, requires_grad=True)

# Training
learning_rate = 0.01
for epoch in range(100):
    y_pred = w * x_train + b
    loss = torch.mean((y_pred - y_train) ** 2)
    loss.backward()

    # Update
    with torch.no_grad():
        w -= learning_rate * w.grad
        b -= learning_rate * b.grad
        w.grad.zero_()
        b.grad.zero_()

print("Trained weight:", w.item())
print("Trained bias:", b.item())


Trained weight: 1.7766615152359009
Trained bias: 0.5076693296432495


In [10]:
import torch

# داده‌ها
x_train = torch.tensor([[1.0], [2.0], [3.0]])
y_train = torch.tensor([[2.0], [4.0], [6.0]])

# مدل: وزن و بایاس با قابلیت گرادیان
w = torch.randn(1, requires_grad=True)
b = torch.tensor(0.0, requires_grad=True)

# آموزش
learning_rate = 0.01
for epoch in range(100):
    y_pred = w * x_train + b
    loss = torch.mean((y_pred - y_train) ** 2)
    loss.backward()

    # به‌روزرسانی وزن و بایاس بدون پیگیری گرادیان
    with torch.no_grad():
        w -= learning_rate * w.grad
        b -= learning_rate * b.grad
        w.grad.zero_()
        b.grad.zero_()

# نمایش مقادیر آموزش‌دیده
print("Trained weight:", w.item())
print("Trained bias:", b.item())

Trained weight: 1.7009762525558472
Trained bias: 0.6797095537185669


### 6️⃣ Bonus ⚡
* Convert a PyTorch tensor to a NumPy array.

* Convert it back to a PyTorch tensor.

🔁 Convert PyTorch tensor → NumPy array

In [13]:
# To do
import torch

tensor = torch.tensor([1.0, 2.0, 3.0])  
numpy_array = tensor.numpy()

print("NumPy Array:", numpy_array)

NumPy Array: [1. 2. 3.]


🔄 Convert NumPy array → PyTorch tensor

In [15]:
import numpy as np 
num_arr = np.array([1 , 5 , 6 ])
tensor = torch.from_numpy(num_arr)
print("pytorch tensor : " , tensor)

pytorch tensor :  tensor([1, 5, 6])
