# 🧠 Assignment: Getting Started with TensorFlow


## 🎯 Goal
This assignment evaluates your basic skills in using TensorFlow, including creating tensors, performing operations, and building a simple model.

### 1️⃣ Setup and Basics
**Task:**

* Install TensorFlow and verify the version.
* Create a simple tensor and print it.

In [2]:
import tensorflow as tf

In [3]:
# Example snippet
import tensorflow as tf

print("TensorFlow version:", tf.__version__)
a = tf.constant([[1, 2], [3, 4]])
print("Tensor a:\n", a)


TensorFlow version: 2.19.0
Tensor a:
 tf.Tensor(
[[1 2]
 [3 4]], shape=(2, 2), dtype=int32)


In [ ]:
# Your turn:
# Create a tensor b with values [[5, 6], [7, 8]] and print its shape.
b = tf.constant([[5, 6], [7, 8]])
print("Tensor a:\n", b)


Tensor a:
 tf.Tensor(
[[5 6]
 [7 8]], shape=(2, 2), dtype=int32)


### 2️⃣ Tensor Operations
**Task:** Perform element-wise addition and multiplication.

In [5]:
# Example snippet
c = a + b
print("Addition:\n", c)

d = a * b
print("Multiplication:\n", d)


Addition:
 tf.Tensor(
[[ 6  8]
 [10 12]], shape=(2, 2), dtype=int32)
Multiplication:
 tf.Tensor(
[[ 5 12]
 [21 32]], shape=(2, 2), dtype=int32)


In [ ]:
# Your turn:
# Compute a @ b (matrix multiplication) and print the result.
e = a @ b
print("matrix multiplication: \n" , e)

matrix multiplication: 
 tf.Tensor(
[[19 22]
 [43 50]], shape=(2, 2), dtype=int32)


### 3️⃣ Random Tensors 🎲
**Task:** Generate a random tensor of shape (3, 3) from a normal distribution and print its mean and standard deviation.

In [7]:
# Example snippet
random_tensor = tf.random.normal([3, 3])
print("Random Tensor:\n", random_tensor)
print("Mean:", tf.reduce_mean(random_tensor))
print("Std Dev:", tf.math.reduce_std(random_tensor))


Random Tensor:
 tf.Tensor(
[[ 2.4778519   1.091282   -1.2910949 ]
 [ 1.723791    0.13134924  0.892447  ]
 [ 0.0541843  -0.05278427 -0.22317024]], shape=(3, 3), dtype=float32)
Mean: tf.Tensor(0.53376174, shape=(), dtype=float32)
Std Dev: tf.Tensor(1.068444, shape=(), dtype=float32)


### 4️⃣ Building a Simple Model 🤖
**Task:** Build a single-layer neural network using tf.keras.Sequential.

In [8]:
# Example snippet
model = tf.keras.Sequential([
    tf.keras.layers.Dense(1, input_shape=(1,))
    ])
model.summary()


c:\Users\Magellan\miniconda3\envs\DsAi\Lib\site-packages\keras\src\layers\core\dense.py:92: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(activity_regularizer=activity_regularizer, **kwargs)


Model: "sequential"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ dense (Dense)                   │ (None, 1)              │             2 │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 2 (8.00 B)

 Trainable params: 2 (8.00 B)

 Non-trainable params: 0 (0.00 B)

In [ ]:
# Your turn:
# Add another dense layer with 5 neurons and relu activation.






### 5️⃣ Bonus ⚡
* Create a tensor with values from 0 to 9 (inclusive).

* Reshape it to shape (2, 5).

* Pint the reshaped tensor.

In [ ]:
# To do





