# 🧠 Assignment: Getting Started with TensorFlow


<p align="center">📢⚠️📂  </p>

<p align="center"> Please name your file using the format: <code>assignmentName_nickname.py/.ipynb</code> (e.g., <code>project1_ali.py</code>) and push it to GitHub with a clear commit message.</p>

<p align="center"> 🚨📝🧠 </p>

------------------------------------------------



## 🎯 Goal
This assignment evaluates your basic skills in using TensorFlow, including creating tensors, performing operations, and building a simple model.

### 1️⃣ Setup and Basics
**Task:**

* Install TensorFlow and verify the version.
* Create a simple tensor and print it.

In [1]:
# Example snippet
import tensorflow as tf

print("TensorFlow version:", tf.__version__)
a = tf.constant([[1, 2], [3, 4]])
print("Tensor a:\n", a)


TensorFlow version: 2.19.0
Tensor a:
 tf.Tensor(
[[1 2]
 [3 4]], shape=(2, 2), dtype=int32)


In [5]:
# Your turn:
# Create a tensor b with values [[5, 6], [7, 8]] and print its shape.

import tensorflow as tf
print("tensorflow version:\n", tf.__version__)

b = tf.constant([[5, 6],[7, 8]])
print("tensor b:\n", b)

tensorflow version:
 2.19.0
tensor b:
 tf.Tensor(
[[5 6]
 [7 8]], shape=(2, 2), dtype=int32)


### 2️⃣ Tensor Operations
**Task:** Perform element-wise addition and multiplication.

In [ ]:
# Example snippet
c = a + b
print("Addition:\n", c)

d = a * b
print("Multiplication:\n", d)


In [7]:
# Your turn:
# Compute a @ b (matrix multiplication) and print the result.


e = a @ b
print("matrix mutliplication:\n", e)

f = tf.matmul(a, b)
print("anoter way to matrix mutliplication:\n", f)


matrix mutliplication:
 tf.Tensor(
[[19 22]
 [43 50]], shape=(2, 2), dtype=int32)
anoter way to matrix mutliplication:
 tf.Tensor(
[[19 22]
 [43 50]], shape=(2, 2), dtype=int32)


### 3️⃣ Random Tensors 🎲
**Task:** Generate a random tensor of shape (3, 3) from a normal distribution and print its mean and standard deviation.

In [12]:
# Example snippet
random_tensor = tf.random.normal([3, 3])
print("Random Tensor:\n", random_tensor)
print("Mean:", tf.reduce_mean(random_tensor))
print("Std Dev:", tf.math.reduce_std(random_tensor))


Random Tensor:
 tf.Tensor(
[[ 0.4567332  -0.68118     0.2229847 ]
 [-1.552968   -1.143649    2.6244414 ]
 [ 0.11049031 -1.9354885  -1.0422286 ]], shape=(3, 3), dtype=float32)
Mean: tf.Tensor(-0.32676274, shape=(), dtype=float32)
Std Dev: tf.Tensor(1.3001397, shape=(), dtype=float32)


### 4️⃣ Building a Simple Model 🤖
**Task:** Build a single-layer neural network using tf.keras.Sequential.

In [13]:
# Example snippet
model = tf.keras.Sequential([
    tf.keras.layers.Dense(1, input_shape=(1,))
])
model.summary()


/usr/local/lib/python3.12/dist-packages/keras/src/layers/core/dense.py:93: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(activity_regularizer=activity_regularizer, **kwargs)


Model: "sequential"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ dense (Dense)                   │ (None, 1)              │             2 │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 2 (8.00 B)

 Trainable params: 2 (8.00 B)

 Non-trainable params: 0 (0.00 B)

In [16]:
# Your turn:
# Add another dense layer with 5 neurons and relu activation.


model = tf.keras.Sequential([
    tf.keras.layers.Dense(units=5 , activation='relu', input_shape=(1,)),
    tf.keras.layers.Dense(units=1)
])
model.summary()


/usr/local/lib/python3.12/dist-packages/keras/src/layers/core/dense.py:93: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(activity_regularizer=activity_regularizer, **kwargs)


Model: "sequential_1"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ dense_1 (Dense)                 │ (None, 5)              │            10 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_2 (Dense)                 │ (None, 1)              │             6 │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 16 (64.00 B)

 Trainable params: 16 (64.00 B)

 Non-trainable params: 0 (0.00 B)

### 5️⃣ Bonus ⚡
* Create a tensor with values from 0 to 9 (inclusive).

* Reshape it to shape (2, 5).

* Pint the reshaped tensor.

In [24]:
# To do



my_tensor = tf.range(10)
print("tensor a:\n", a)

reshaped_tensor = tf.reshape(my_tensor, shape=(2, 5))
print("reshaped tensor:\n", reshaped_tensor.numpy())




tensor a:
 tf.Tensor([0 1 2 3 4 5 6 7 8 9], shape=(10,), dtype=int32)
reshaped tensor:
 [[0 1 2 3 4]
 [5 6 7 8 9]]
