# 🧠 Assignment: Getting Started with TensorFlow


## 🎯 Goal
This assignment evaluates your basic skills in using TensorFlow, including creating tensors, performing operations, and building a simple model.

### 1️⃣ Setup and Basics
**Task:**

* Install TensorFlow and verify the version.
* Create a simple tensor and print it.

In [1]:
# Example snippet
import tensorflow as tf

print("TensorFlow version:", tf.__version__)
a = tf.constant([[1, 2], [3, 4]])
print("Tensor a:\n", a)


TensorFlow version: 2.18.0
Tensor a:
 tf.Tensor(
[[1 2]
 [3 4]], shape=(2, 2), dtype=int32)


In [2]:
# Your turn:
# Create a tensor b with values [[5, 6], [7, 8]] and print its shape.
b=tf.constant([[5,6],[7,8]])
print(b)
print(b.shape)



tf.Tensor(
[[5 6]
 [7 8]], shape=(2, 2), dtype=int32)
(2, 2)


### 2️⃣ Tensor Operations
**Task:** Perform element-wise addition and multiplication.

In [3]:
# Example snippet
c = a + b
print("Addition:\n", c)

d = a * b
print("Multiplication:\n", d)


Addition:
 tf.Tensor(
[[ 6  8]
 [10 12]], shape=(2, 2), dtype=int32)
Multiplication:
 tf.Tensor(
[[ 5 12]
 [21 32]], shape=(2, 2), dtype=int32)


In [4]:
# Your turn:
# Compute a @ b (matrix multiplication) and print the result.
m=a@b
print(m)




tf.Tensor(
[[19 22]
 [43 50]], shape=(2, 2), dtype=int32)


### 3️⃣ Random Tensors 🎲
**Task:** Generate a random tensor of shape (3, 3) from a normal distribution and print its mean and standard deviation.

In [5]:
# Example snippet
random_tensor = tf.random.normal([3, 3])
print("Random Tensor:\n", random_tensor)
print("Mean:", tf.reduce_mean(random_tensor))
print("Std Dev:", tf.math.reduce_std(random_tensor))


Random Tensor:
 tf.Tensor(
[[ 1.3571868  -0.6091366  -0.61158186]
 [ 1.7426014  -0.04790685  0.81934994]
 [ 1.32141    -0.4158888   0.26323682]], shape=(3, 3), dtype=float32)
Mean: tf.Tensor(0.42436343, shape=(), dtype=float32)
Std Dev: tf.Tensor(0.86055195, shape=(), dtype=float32)


### 4️⃣ Building a Simple Model 🤖
**Task:** Build a single-layer neural network using tf.keras.Sequential.

In [6]:
# Example snippet
model = tf.keras.Sequential([
    tf.keras.layers.Dense(1, input_shape=(1,))
])
model.summary()


/usr/local/lib/python3.11/dist-packages/keras/src/layers/core/dense.py:87: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(activity_regularizer=activity_regularizer, **kwargs)


Model: "sequential"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ dense (Dense)                   │ (None, 1)              │             2 │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 2 (8.00 B)

 Trainable params: 2 (8.00 B)

 Non-trainable params: 0 (0.00 B)

In [7]:
# Your turn:
# Add another dense layer with 5 neurons and relu activation.

model.add(tf.keras.layers.Dense(5,activation='relu'))
model.summary()




Model: "sequential"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ dense (Dense)                   │ (None, 1)              │             2 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_1 (Dense)                 │ (None, 5)              │            10 │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 12 (48.00 B)

 Trainable params: 12 (48.00 B)

 Non-trainable params: 0 (0.00 B)

### 5️⃣ Bonus ⚡
* Create a tensor with values from 0 to 9 (inclusive).

* Reshape it to shape (2, 5).

* Pint the reshaped tensor.

In [8]:
# To do

a=tf.range(10)
print(a)
b=tf.reshape(a,(2,5))
print(b)





tf.Tensor([0 1 2 3 4 5 6 7 8 9], shape=(10,), dtype=int32)
tf.Tensor(
[[0 1 2 3 4]
 [5 6 7 8 9]], shape=(2, 5), dtype=int32)
